#!/usr/bin/python
from distutils.core import setup, Extension
import sys
import os
import fnmatch

SOURCES = ['horus.i']
dir = '../src/'
archivos = os.listdir(dir)
for archivo in archivos:
	if fnmatch.fnmatch(archivo, '*.cpp') and archivo <> 'main.cpp':
		SOURCES.append(os.path.join(dir, archivo))

# Note: libhorus_cuda.a is generated by the Makefile!!!
LIBRARIES = ['cv', 'cxcore', 'highgui', 'horus_cuda']

print SOURCES

options = {}
options['sources'] = SOURCES
options['libraries'] = LIBRARIES
options['swig_opts'] = ['-c++']
options['library_dirs'] = ['.']

if os.name == 'posix':
	pass
elif os.name == 'nt':
	options['include_dirs'] = ['c:\\Archivos de programa\\opencv\\__include']
	options['library_dirs'] = ['c:\\Archivos de programa\\opencv\\lib']
else:
	raise Exception("Unsuported platform")

horus_ext = Extension('_horus', **options)

setup(name="horus",
	  version="0.1",
	  author="Marcelo L. Mottalli",
	  ext_modules=[horus_ext],
	  py_modules=["horus"]
	)
