/*
 * videoprocessor.cpp
 *
 *  Created on: Jun 13, 2009
 *      Author: marcelo
 */

#include "videoprocessor.h"
#include <stdexcept>
#include <iostream>
#include <cmath>

VideoProcessor::VideoProcessor()
{
	this->lastStatus = DEFOCUSED;
	this->templateWaitCount = 0;
	this->waitingBestTemplate = false;
	this->waitingFrames = 40;
	this->framesToSkip = 0;
}

VideoProcessor::~VideoProcessor()
{
}

VideoProcessor::VideoStatus VideoProcessor::processFrame(const Mat& frame)
{
	frame.copyTo(this->lastFrame);

	if (this->framesToSkip > 0) {
		this->framesToSkip--;
		this->lastStatus = UNPROCESSED;
		return UNPROCESSED;
	}

	if (frame.channels() == 1) {
		this->lastFrameBW = this->lastFrame;
	} else {
		cvtColor(frame, this->lastFrameBW, CV_BGR2GRAY);
	}
	
	this->lastStatus = this->doProcess(frame);
	
	if (this->lastStatus == FOCUSED_IRIS && !this->waitingBestTemplate) {		// A new iris has been detected. Start the template generation process
		this->waitingBestTemplate = true;
		this->templateBuffer.clear();			// Create a new buffer to store the subsequent templates
	}
	
	if (this->waitingBestTemplate) {
		if (this->lastStatus == FOCUSED_IRIS) {
			// Pushes the template generated by this iris to the list.
			CapturedTemplate capturedTemplate;
			this->lastFrameBW.copyTo(capturedTemplate.image);
			capturedTemplate.irisTemplate = this->irisEncoder.generateTemplate(this->lastFrameBW, this->lastSegmentationResult);
			capturedTemplate.quality = this->lastIrisQuality;
			capturedTemplate.segmentationResult = this->lastSegmentationResult;

			this->templateBuffer.push_back(capturedTemplate);

			if (this->templateBuffer.size() == 1) this->bestTemplateIdx = 0;

			if (this->lastIrisQuality > this->templateBuffer[this->bestTemplateIdx].quality) {		// Got a better quality image
				this->bestTemplateIdx = templateBuffer.size()-1;
				this->templateWaitCount = 0;
			}

			this->lastTemplate = capturedTemplate.irisTemplate;
		}
		
		this->templateWaitCount++;
		if (this->templateWaitCount >= this->parameters.bestFrameWaitCount) {
			// Got the iris template with the best quality
			this->lastStatus = GOT_TEMPLATE;
			this->templateWaitCount = 0;
			this->waitingBestTemplate = false;
			
			// Wait before processing more images
			this->framesToSkip = this->waitingFrames;
		}
	}
	
	return this->lastStatus;
}

VideoProcessor::VideoStatus VideoProcessor::doProcess(const Mat& frame)
{
	const Mat& image = this->lastFrameBW;

	this->lastFocusScore = this->qualityChecker.checkFocus(image);
	if (this->lastFocusScore < this->parameters.focusThreshold) {
		return DEFOCUSED;
	}

	if (this->parameters.interlacedVideo) {
		double interlacedCorrelation = this->qualityChecker.interlacedCorrelation(image);
		if (interlacedCorrelation < this->parameters.correlationThreshold) {
			return INTERLACED;
		}
	}

	this->lastSegmentationResult = segmentator.segmentImage(image);
	if (this->parameters.segmentEyelids) {
		segmentator.segmentEyelids(image, this->lastSegmentationResult);
	}

	this->lastIrisHeuristics = qualityChecker.validateIris(image, this->lastSegmentationResult);
	if (this->lastIrisHeuristics != QualityChecker::HAS_IRIS) {
		// No iris found on the image, or the segmentation is incorrect
		return FOCUSED_NO_IRIS;
	}

	this->lastIrisQuality = qualityChecker.getIrisQuality(image, this->lastSegmentationResult);
	if (this->lastIrisQuality < this->parameters.minimumContourQuality) {
		// The image is kind of focused but the iris doesn't have enough quality
		// TODO: Check whether to return IRIS_TOO_FAR or IRIS_TOO_CLOSE

		return IRIS_LOW_QUALITY;
	}

	// At this point we have a good quality image and we have enough reasons to believe
	// it's properly segmented.
	return FOCUSED_IRIS;
}

IrisTemplate VideoProcessor::getBestTemplate() const
{
	return this->templateBuffer[this->bestTemplateIdx].irisTemplate;
}

IrisTemplate VideoProcessor::getAverageTemplate() const
{
	vector<const IrisTemplate*> templates;
	for (vector<CapturedTemplate>::const_iterator it = this->templateBuffer.begin(); it != this->templateBuffer.end(); it++) {
		templates.push_back( &((*it).irisTemplate) );
	}
	return IrisEncoder::averageTemplates(templates);
}

const Mat& VideoProcessor::getBestTemplateFrame() const
{
	return this->templateBuffer[this->bestTemplateIdx].image;
}

const SegmentationResult& VideoProcessor::getBestTemplateSegmentation() const
{
	return this->templateBuffer[this->bestTemplateIdx].segmentationResult;
}
